// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *about → Experience*
 */
export interface AboutDocumentDataExperienceItem {
  /**
   * Logo field in *about → Experience*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *about → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *about → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Year field in *about → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;
}

/**
 * Item in *about → Education*
 */
export interface AboutDocumentDataEducationItem {
  /**
   * Logo field in *about → Education*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.education[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *about → Education*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.education[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *about → Education*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.education[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Year field in *about → Education*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.education[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;
}

/**
 * Item in *about → Passion*
 */
export interface AboutDocumentDataPassionItem {
  /**
   * Title field in *about → Passion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.passion[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Clubs field in *about → Passion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.passion[].clubs
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  clubs: prismic.KeyTextField;

  /**
   * Description field in *about → Passion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.passion[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Instagram field in *about → Passion*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.passion[].instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;
}

/**
 * Item in *about → Volleyball*
 */
export interface AboutDocumentDataVolleyballItem {
  /**
   * Image field in *about → Volleyball*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.volleyball[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type AboutDocumentDataSlicesSlice = AboutItemSlice;

/**
 * Content for about documents
 */
interface AboutDocumentData {
  /**
   * Experience field in *about*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience: prismic.GroupField<Simplify<AboutDocumentDataExperienceItem>>;

  /**
   * Education field in *about*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.education[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  education: prismic.GroupField<Simplify<AboutDocumentDataEducationItem>>;

  /**
   * Passion field in *about*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.passion[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  passion: prismic.GroupField<Simplify<AboutDocumentDataPassionItem>>;

  /**
   * Volleyball field in *about*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.volleyball[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  volleyball: prismic.GroupField<Simplify<AboutDocumentDataVolleyballItem>>;

  /**
   * Slice Zone field in *about*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *about*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomeDocumentDataSlicesSlice =
  | CenterTextSlice
  | HeroSlice
  | SwiperSliderSlice
  | HeaderTextSlice
  | ProjectCardSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ProjectsDocumentDataSlicesSlice = ProjectCardSlice | SwiperSliderSlice;

/**
 * Content for projects documents
 */
interface ProjectsDocumentData {
  /**
   * Slice Zone field in *projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | HomeDocument | ProjectsDocument;

/**
 * Primary content in *AboutItem → Primary*
 */
export interface AboutItemSliceDefaultPrimary {
  /**
   * Category field in *AboutItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_item.primary.category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * Logo field in *AboutItem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_item.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *AboutItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_item.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *AboutItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_item.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Year field in *AboutItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_item.primary.year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;
}

/**
 * Default variation for AboutItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutItem*
 */
type AboutItemSliceVariation = AboutItemSliceDefault;

/**
 * AboutItem Shared Slice
 *
 * - **API ID**: `about_item`
 * - **Description**: AboutItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutItemSlice = prismic.SharedSlice<
  "about_item",
  AboutItemSliceVariation
>;

/**
 * Primary content in *CenterText → Primary*
 */
export interface CenterTextSliceDefaultPrimary {
  /**
   * Text field in *CenterText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: center_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for CenterText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenterTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CenterTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CenterText*
 */
type CenterTextSliceVariation = CenterTextSliceDefault;

/**
 * CenterText Shared Slice
 *
 * - **API ID**: `center_text`
 * - **Description**: CenterText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CenterTextSlice = prismic.SharedSlice<
  "center_text",
  CenterTextSliceVariation
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceDefaultPrimary {
  /**
   * Header field in *HeaderText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;
}

/**
 * Default variation for HeaderText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderText*
 */
type HeaderTextSliceVariation = HeaderTextSliceDefault;

/**
 * HeaderText Shared Slice
 *
 * - **API ID**: `header_text`
 * - **Description**: HeaderText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSlice = prismic.SharedSlice<
  "header_text",
  HeaderTextSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Headshot field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.headshot
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  headshot: prismic.ImageField<never>;

  /**
   * Name field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Occupation field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.occupation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  occupation: prismic.KeyTextField;

  /**
   * Location field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageGallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
  /**
   * Image field in *ImageGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageGallerySliceDefaultItem>
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySlice = prismic.SharedSlice<
  "image_gallery",
  ImageGallerySliceVariation
>;

/**
 * Primary content in *ProjectCard → Primary*
 */
export interface ProjectCardSliceDefaultPrimary {
  /**
   * Name field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Date field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Team field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.team
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  team: prismic.KeyTextField;

  /**
   * Skills field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.skills
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skills: prismic.KeyTextField;

  /**
   * Reason field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.reason
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reason: prismic.KeyTextField;

  /**
   * Slug field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectCard → Items*
 */
export interface ProjectCardSliceDefaultItem {
  /**
   * Image field in *ProjectCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectCardSliceDefaultPrimary>,
  Simplify<ProjectCardSliceDefaultItem>
>;

/**
 * Right variation for ProjectCard Slice
 *
 * - **API ID**: `right`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardSliceRight = prismic.SharedSliceVariation<
  "right",
  Record<string, never>,
  never
>;

/**
 * Left variation for ProjectCard Slice
 *
 * - **API ID**: `left`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardSliceLeft = prismic.SharedSliceVariation<
  "left",
  Record<string, never>,
  never
>;

/**
 * Primary content in *ProjectCard → Primary*
 */
export interface ProjectCardSliceDetailedPrimary {
  /**
   * Name field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Date field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Team field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.team
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  team: prismic.KeyTextField;

  /**
   * Reason field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.reason
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reason: prismic.KeyTextField;

  /**
   * Slug field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * blurp field in *ProjectCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.blurp
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blurp: prismic.RichTextField;
}

/**
 * Primary content in *ProjectCard → Items*
 */
export interface ProjectCardSliceDetailedItem {
  /**
   * Image field in *ProjectCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Detailed variation for ProjectCard Slice
 *
 * - **API ID**: `detailed`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardSliceDetailed = prismic.SharedSliceVariation<
  "detailed",
  Simplify<ProjectCardSliceDetailedPrimary>,
  Simplify<ProjectCardSliceDetailedItem>
>;

/**
 * Primary content in *ProjectCard → Primary*
 */
export interface ProjectCardSliceHeroPrimary {
  /**
   * Name field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Date field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Skills field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.skills
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skills: prismic.KeyTextField;

  /**
   * Slug field in *ProjectCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectCard → Items*
 */
export interface ProjectCardSliceHeroItem {
  /**
   * Image field in *ProjectCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Hero variation for ProjectCard Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardSliceHero = prismic.SharedSliceVariation<
  "hero",
  Simplify<ProjectCardSliceHeroPrimary>,
  Simplify<ProjectCardSliceHeroItem>
>;

/**
 * Slice variation for *ProjectCard*
 */
type ProjectCardSliceVariation =
  | ProjectCardSliceDefault
  | ProjectCardSliceRight
  | ProjectCardSliceLeft
  | ProjectCardSliceDetailed
  | ProjectCardSliceHero;

/**
 * ProjectCard Shared Slice
 *
 * - **API ID**: `project_card`
 * - **Description**: ProjectCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardSlice = prismic.SharedSlice<
  "project_card",
  ProjectCardSliceVariation
>;

/**
 * Primary content in *SwiperSlider → Items*
 */
export interface SwiperSliderSliceDefaultItem {
  /**
   * Logo field in *SwiperSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: swiper_slider.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo: prismic.KeyTextField;

  /**
   * LogoName field in *SwiperSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: swiper_slider.items[].logoname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logoname: prismic.KeyTextField;
}

/**
 * Default variation for SwiperSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SwiperSliderSliceDefaultItem>
>;

/**
 * Primary content in *SwiperSlider → Primary*
 */
export interface SwiperSliderSliceSmallerPrimary {
  /**
   * Project field in *SwiperSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: swiper_slider.primary.project
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project: prismic.KeyTextField;
}

/**
 * Primary content in *SwiperSlider → Items*
 */
export interface SwiperSliderSliceSmallerItem {
  /**
   * Logo field in *SwiperSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: swiper_slider.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo: prismic.KeyTextField;

  /**
   * LogoName field in *SwiperSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: swiper_slider.items[].logoname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logoname: prismic.KeyTextField;
}

/**
 * Smaller variation for SwiperSlider Slice
 *
 * - **API ID**: `smaller`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliderSliceSmaller = prismic.SharedSliceVariation<
  "smaller",
  Simplify<SwiperSliderSliceSmallerPrimary>,
  Simplify<SwiperSliderSliceSmallerItem>
>;

/**
 * Slice variation for *SwiperSlider*
 */
type SwiperSliderSliceVariation =
  | SwiperSliderSliceDefault
  | SwiperSliderSliceSmaller;

/**
 * SwiperSlider Shared Slice
 *
 * - **API ID**: `swiper_slider`
 * - **Description**: SwiperSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SwiperSliderSlice = prismic.SharedSlice<
  "swiper_slider",
  SwiperSliderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutItemSlice,
      AboutItemSliceDefaultPrimary,
      AboutItemSliceVariation,
      AboutItemSliceDefault,
      CenterTextSlice,
      CenterTextSliceDefaultPrimary,
      CenterTextSliceVariation,
      CenterTextSliceDefault,
      HeaderTextSlice,
      HeaderTextSliceDefaultPrimary,
      HeaderTextSliceVariation,
      HeaderTextSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageGallerySlice,
      ImageGallerySliceDefaultItem,
      ImageGallerySliceVariation,
      ImageGallerySliceDefault,
      ProjectCardSlice,
      ProjectCardSliceDefaultPrimary,
      ProjectCardSliceDefaultItem,
      ProjectCardSliceDetailedPrimary,
      ProjectCardSliceDetailedItem,
      ProjectCardSliceHeroPrimary,
      ProjectCardSliceHeroItem,
      ProjectCardSliceVariation,
      ProjectCardSliceDefault,
      ProjectCardSliceRight,
      ProjectCardSliceLeft,
      ProjectCardSliceDetailed,
      ProjectCardSliceHero,
      SwiperSliderSlice,
      SwiperSliderSliceDefaultItem,
      SwiperSliderSliceSmallerPrimary,
      SwiperSliderSliceSmallerItem,
      SwiperSliderSliceVariation,
      SwiperSliderSliceDefault,
      SwiperSliderSliceSmaller,
    };
  }
}
