// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  repeat: defineAsyncComponent(() => import("./Repeat/index.vue")),
  slider_slice: defineAsyncComponent(() => import("./SliderSlice/index.vue")),
});
