// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_item: defineAsyncComponent(() => import("./AboutItem/index.vue")),
  center_text: defineAsyncComponent(() => import("./CenterText/index.vue")),
  header_text: defineAsyncComponent(() => import("./HeaderText/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  image_gallery: defineAsyncComponent(() => import("./ImageGallery/index.vue")),
  project_card: defineAsyncComponent(() => import("./ProjectCard/index.vue")),
  swiper_slider: defineAsyncComponent(() => import("./SwiperSlider/index.vue")),
});
